package org.quiltmc.internal.dummy_plugin;

import org.quiltmc.enigma.api.EnigmaPlugin;
import org.quiltmc.enigma.api.EnigmaPluginContext;
import org.quiltmc.enigma.util.Version;

/**
 * A dummy plugin to be compiled against the current Enigma version and run against the copied+bumped Enigma version
 * generated by the build script to test default {@link EnigmaPlugin#supportsEnigmaVersion(Version)} implementation.
 */
public class DummyEnigmaPlugin implements EnigmaPlugin {
	public static final String NAME = "Dummy Enigma Plugin";

	@Override
	public void init(EnigmaPluginContext ctx) {
		throw new UnsupportedOperationException(DummyEnigmaPlugin.class.getSimpleName() + " initialized!");
	}

	@Override
	public String getName() {
		return NAME;
	}
}
