package org.quiltmc.internal.dummy_plugin;

import org.quiltmc.enigma.api.Enigma;
import org.quiltmc.enigma.api.EnigmaPlugin;
import org.quiltmc.enigma.api.EnigmaPluginContext;
import org.quiltmc.enigma.util.Version;

import javax.annotation.Nonnull;

/**
 * A dummy plugin to be compiled against the current Enigma version and run against the copied+bumped Enigma version
 * generated by the build script to test the recommended {@link EnigmaPlugin#supportsEnigmaVersion(Version)}
 * implementation.
 */
public class DummyEnigmaPlugin implements EnigmaPlugin {
	public static final String NAME = "Dummy Enigma Plugin";

	@Override
	public void init(EnigmaPluginContext ctx) {
		throw new UnsupportedOperationException(DummyEnigmaPlugin.class.getSimpleName() + " initialized!");
	}

	@Override
	public boolean supportsEnigmaVersion(@Nonnull Version enigmaVersion) {
		return Enigma.MAJOR_VERSION == enigmaVersion.major()
			&& Enigma.MINOR_VERSION == enigmaVersion.minor();
	}

	@Override
	public String getName() {
		return NAME;
	}
}
