name: test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        java: [17-jdk, 19-jdk]
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: update apt
        run: apt-get update
      - name: install xvfb
        run: apt-get install -y xvfb libxrender1 libxtst6 libxi6
      - name: run tests
        run: xvfb-run ./gradlew completeTestGui --stacktrace --warning-mode fail
        env:
          SNAPSHOTS_URL: ${{ secrets.SNAPSHOTS_URL }}
          SNAPSHOTS_USERNAME: ${{ secrets.SNAPSHOTS_USERNAME }}
          SNAPSHOTS_PASSWORD: ${{ secrets.SNAPSHOTS_PASSWORD }}
